import { useState, useCallback } from 'react';
import { Sparkles, PlayCircle, Loader2, Zap, Moon, Target, Music, Coffee, PartyPopper } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { ScrollArea } from '@/components/ui/scroll-area';
import { toast } from 'sonner';
import { useAuth } from '@/contexts/AuthContext';
import { createPlaylist, addTracksToPlaylist, getCurrentUser } from '@/lib/spotify-api';
import { cn } from '@/lib/utils';

export interface ContextConfig {
  key: string;
  name: string;
  description: string;
  icon: React.ReactNode;
  bpmStart: number;
  bpmEnd: number;
  energyStart: number;
  energyEnd: number;
  undergroundRatio: number;
  progression: 'build' | 'plateau' | 'descend' | 'steady';
}

export interface GeneratedTrack {
  track_id: string;
  name: string;
  artist: string;
  tempo: number | null;
  energy: number | null;
  popularity: number | null;
  position: number;
}

interface ContextPlaylistGeneratorProps {
  onGenerate: (context: ContextConfig, durationMinutes: number) => Promise<GeneratedTrack[]>;
}

const CONTEXTS: ContextConfig[] = [
  {
    key: 'event_opener',
    name: 'Event Opener',
    description: 'Build energy gradually, start approachable',
    icon: <Target className="w-5 h-5" />,
    bpmStart: 95,
    bpmEnd: 115,
    energyStart: 50,
    energyEnd: 75,
    undergroundRatio: 0.4,
    progression: 'build',
  },
  {
    key: 'peak_energy',
    name: 'Peak Energy',
    description: 'High BPM, high energy, maximum danceability',
    icon: <Zap className="w-5 h-5" />,
    bpmStart: 120,
    bpmEnd: 140,
    energyStart: 75,
    energyEnd: 95,
    undergroundRatio: 0.3,
    progression: 'plateau',
  },
  {
    key: 'wind_down',
    name: 'Wind Down',
    description: 'Gradually decrease energy, smooth transitions',
    icon: <Moon className="w-5 h-5" />,
    bpmStart: 110,
    bpmEnd: 90,
    energyStart: 70,
    energyEnd: 40,
    undergroundRatio: 0.5,
    progression: 'descend',
  },
  {
    key: 'creative_focus',
    name: 'Creative Focus',
    description: 'Mid-tempo, lower energy, instrumental-friendly',
    icon: <Coffee className="w-5 h-5" />,
    bpmStart: 90,
    bpmEnd: 105,
    energyStart: 40,
    energyEnd: 60,
    undergroundRatio: 0.6,
    progression: 'steady',
  },
  {
    key: 'late_night',
    name: 'Late Night Vibes',
    description: 'Emotional, moderate tempo, positive valence',
    icon: <PartyPopper className="w-5 h-5" />,
    bpmStart: 100,
    bpmEnd: 115,
    energyStart: 50,
    energyEnd: 65,
    undergroundRatio: 0.5,
    progression: 'build',
  },
];

const ContextPlaylistGenerator = ({ onGenerate }: ContextPlaylistGeneratorProps) => {
  const { accessToken } = useAuth();
  const [selectedContext, setSelectedContext] = useState<ContextConfig | null>(null);
  const [duration, setDuration] = useState(60);
  const [generatedTracks, setGeneratedTracks] = useState<GeneratedTrack[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isCreatingPlaylist, setIsCreatingPlaylist] = useState(false);

  const estimatedTracks = Math.ceil(duration / 3.5);

  const handleGenerate = useCallback(async () => {
    if (!selectedContext) {
      toast.error('Please select a context first');
      return;
    }

    setIsGenerating(true);
    try {
      const tracks = await onGenerate(selectedContext, duration);
      setGeneratedTracks(tracks);
      if (tracks.length === 0) {
        toast.info('No matching tracks found. Try a different context.');
      } else {
        toast.success(`Generated ${tracks.length} tracks for ${selectedContext.name}!`);
      }
    } catch (err) {
      console.error('Generation error:', err);
      toast.error('Failed to generate playlist');
    } finally {
      setIsGenerating(false);
    }
  }, [selectedContext, duration, onGenerate]);

  const handleSaveToSpotify = useCallback(async () => {
    if (!accessToken || generatedTracks.length === 0 || !selectedContext) return;

    setIsCreatingPlaylist(true);
    try {
      const user = await getCurrentUser(accessToken);
      
      const playlistName = `${selectedContext.name} - ${new Date().toLocaleDateString()}`;
      const description = `${selectedContext.description} | ${duration} mins | Generated by Music DNA`;
      
      const newPlaylist = await createPlaylist(accessToken, user.id, playlistName, description, false);
      
      const trackUris = generatedTracks.map(t => `spotify:track:${t.track_id}`);
      await addTracksToPlaylist(accessToken, newPlaylist.id, trackUris);
      
      toast.success(`Saved "${playlistName}" to Spotify!`);
    } catch (err) {
      console.error('Failed to save playlist:', err);
      toast.error('Failed to save playlist');
    } finally {
      setIsCreatingPlaylist(false);
    }
  }, [accessToken, generatedTracks, selectedContext, duration]);

  const getProgressionLabel = (p: string) => {
    switch (p) {
      case 'build': return '📈 Builds Up';
      case 'plateau': return '➡️ Steady High';
      case 'descend': return '📉 Winds Down';
      case 'steady': return '➡️ Consistent';
      default: return p;
    }
  };

  return (
    <Card className="border-primary/20 bg-gradient-to-br from-card via-card to-primary/5">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-lg">
          <Sparkles className="w-5 h-5 text-primary" />
          Context Playlist Generator
        </CardTitle>
        <CardDescription>
          AI-powered playlists for specific moods and events
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        {/* Context Selection */}
        <div className="space-y-3">
          <Label className="text-sm font-medium">Select Context</Label>
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-2">
            {CONTEXTS.map((ctx) => (
              <button
                key={ctx.key}
                onClick={() => setSelectedContext(ctx)}
                className={cn(
                  "flex flex-col items-center gap-2 p-3 rounded-lg border transition-all",
                  selectedContext?.key === ctx.key
                    ? "border-primary bg-primary/10 text-primary"
                    : "border-border hover:border-primary/50 hover:bg-muted/50"
                )}
              >
                {ctx.icon}
                <span className="text-xs font-medium text-center">{ctx.name}</span>
              </button>
            ))}
          </div>
        </div>

        {/* Context Details */}
        {selectedContext && (
          <div className="p-4 rounded-lg bg-muted/50 space-y-2">
            <div className="flex items-center gap-2 mb-2">
              {selectedContext.icon}
              <span className="font-medium">{selectedContext.name}</span>
            </div>
            <p className="text-sm text-muted-foreground">{selectedContext.description}</p>
            <div className="flex flex-wrap gap-2 mt-3">
              <Badge variant="secondary">
                BPM: {selectedContext.bpmStart}-{selectedContext.bpmEnd}
              </Badge>
              <Badge variant="outline">
                Energy: {selectedContext.energyStart}-{selectedContext.energyEnd}%
              </Badge>
              <Badge variant="outline">
                {getProgressionLabel(selectedContext.progression)}
              </Badge>
              <Badge variant="outline">
                {Math.round(selectedContext.undergroundRatio * 100)}% Underground
              </Badge>
            </div>
          </div>
        )}

        {/* Duration Input */}
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2">
            <Label className="text-sm">Duration:</Label>
            <Input
              type="number"
              value={duration}
              onChange={(e) => setDuration(Math.min(180, Math.max(15, Number(e.target.value))))}
              className="w-20 h-8 text-sm"
              min={15}
              max={180}
            />
            <span className="text-sm text-muted-foreground">minutes</span>
          </div>
          <span className="text-sm text-muted-foreground">
            ≈ {estimatedTracks} tracks
          </span>
        </div>

        {/* Generate Button */}
        <Button 
          onClick={handleGenerate} 
          disabled={!selectedContext || isGenerating}
          className="w-full"
        >
          {isGenerating ? (
            <>
              <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <Sparkles className="w-4 h-4 mr-2" />
              Generate Playlist
            </>
          )}
        </Button>

        {/* Generated Tracks Preview */}
        {generatedTracks.length > 0 && selectedContext && (
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-foreground">
                  {generatedTracks.length} tracks generated
                </p>
                <p className="text-xs text-muted-foreground">
                  Approx. {Math.round(generatedTracks.length * 3.5)} minutes
                </p>
              </div>
              <Button 
                onClick={handleSaveToSpotify}
                disabled={isCreatingPlaylist}
                size="sm"
              >
                {isCreatingPlaylist ? (
                  <>
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    Saving...
                  </>
                ) : (
                  <>
                    <PlayCircle className="w-4 h-4 mr-2" />
                    Save to Spotify
                  </>
                )}
              </Button>
            </div>

            <ScrollArea className="h-[280px] rounded-md border">
              <div className="p-4 space-y-2">
                {generatedTracks.map((track, i) => (
                  <div
                    key={track.track_id}
                    className="flex items-center gap-3 p-2 rounded-lg hover:bg-muted/50 transition-colors"
                  >
                    <span className="text-xs text-muted-foreground w-6">{i + 1}</span>
                    <Music className="w-4 h-4 text-muted-foreground flex-shrink-0" />
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium truncate">{track.name}</p>
                      <p className="text-xs text-muted-foreground truncate">{track.artist}</p>
                    </div>
                    <div className="flex items-center gap-2 flex-shrink-0">
                      {track.tempo && (
                        <Badge variant="secondary" className="text-xs">
                          {Math.round(track.tempo)} BPM
                        </Badge>
                      )}
                      {track.energy && (
                        <Badge variant="outline" className="text-xs">
                          {Math.round(track.energy * 100)}%
                        </Badge>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </ScrollArea>
          </div>
        )}
      </CardContent>
    </Card>
  );
};

export default ContextPlaylistGenerator;
