import { useState, useCallback } from 'react';
import { Search, Filter, Music2, Gem, TrendingDown, PlayCircle, Loader2 } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Slider } from '@/components/ui/slider';
import { Switch } from '@/components/ui/switch';
import { Badge } from '@/components/ui/badge';
import { ScrollArea } from '@/components/ui/scroll-area';
import { toast } from 'sonner';
import { useAuth } from '@/contexts/AuthContext';
import { createPlaylist, addTracksToPlaylist, getCurrentUser } from '@/lib/spotify-api';

export interface DiscoveryFilters {
  minBpm: number;
  maxBpm: number;
  minEnergy: number;
  maxEnergy: number;
  minDance: number;
  maxDance: number;
  undergroundOnly: boolean;
  limit: number;
}

export interface TrackResult {
  track_id: string;
  name: string;
  artist: string;
  album: string | null;
  tempo: number | null;
  energy: number | null;
  danceability: number | null;
  popularity: number | null;
}

interface SmartDiscoveryEngineProps {
  onSearch: (filters: DiscoveryFilters) => Promise<TrackResult[]>;
}

const SmartDiscoveryEngine = ({ onSearch }: SmartDiscoveryEngineProps) => {
  const { accessToken } = useAuth();
  const [filters, setFilters] = useState<DiscoveryFilters>({
    minBpm: 90,
    maxBpm: 130,
    minEnergy: 50,
    maxEnergy: 85,
    minDance: 60,
    maxDance: 100,
    undergroundOnly: true,
    limit: 30,
  });

  const [results, setResults] = useState<TrackResult[]>([]);
  const [isSearching, setIsSearching] = useState(false);
  const [isCreatingPlaylist, setIsCreatingPlaylist] = useState(false);

  const handleSearch = useCallback(async () => {
    setIsSearching(true);
    try {
      const tracks = await onSearch(filters);
      setResults(tracks);
      if (tracks.length === 0) {
        toast.info('No tracks match your criteria. Try adjusting filters.');
      } else {
        toast.success(`Found ${tracks.length} matching tracks!`);
      }
    } catch (err) {
      console.error('Search error:', err);
      toast.error('Failed to search tracks');
    } finally {
      setIsSearching(false);
    }
  }, [filters, onSearch]);

  const handleCreatePlaylist = useCallback(async () => {
    if (!accessToken || results.length === 0) return;

    setIsCreatingPlaylist(true);
    try {
      const user = await getCurrentUser(accessToken);
      
      const playlistName = `Smart Discovery - ${new Date().toLocaleDateString()}`;
      const description = `BPM: ${filters.minBpm}-${filters.maxBpm} | Energy: ${filters.minEnergy}-${filters.maxEnergy}% | ${filters.undergroundOnly ? 'Underground gems' : 'All tracks'} | Generated by Music DNA`;
      
      const newPlaylist = await createPlaylist(accessToken, user.id, playlistName, description, false);
      
      const trackUris = results.map(t => `spotify:track:${t.track_id}`);
      await addTracksToPlaylist(accessToken, newPlaylist.id, trackUris);
      
      toast.success(`Created "${playlistName}" with ${results.length} tracks!`);
    } catch (err) {
      console.error('Failed to create playlist:', err);
      toast.error('Failed to create playlist');
    } finally {
      setIsCreatingPlaylist(false);
    }
  }, [accessToken, results, filters]);

  return (
    <Card className="border-primary/20 bg-gradient-to-br from-card via-card to-primary/5">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-lg">
          <Search className="w-5 h-5 text-primary" />
          Smart Discovery Engine
        </CardTitle>
        <CardDescription>
          Find tracks from your library matching specific criteria
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        {/* Filters Grid */}
        <div className="grid gap-6 md:grid-cols-2">
          {/* BPM Range */}
          <div className="space-y-3">
            <Label className="text-sm font-medium">
              BPM Range: {filters.minBpm} - {filters.maxBpm}
            </Label>
            <div className="flex items-center gap-3">
              <Input
                type="number"
                value={filters.minBpm}
                onChange={(e) => setFilters(prev => ({ ...prev, minBpm: Number(e.target.value) }))}
                className="w-20 h-8 text-sm"
                min={50}
                max={200}
              />
              <Slider
                value={[filters.minBpm, filters.maxBpm]}
                onValueChange={([min, max]) => setFilters(prev => ({ ...prev, minBpm: min, maxBpm: max }))}
                min={50}
                max={200}
                step={5}
                className="flex-1"
              />
              <Input
                type="number"
                value={filters.maxBpm}
                onChange={(e) => setFilters(prev => ({ ...prev, maxBpm: Number(e.target.value) }))}
                className="w-20 h-8 text-sm"
                min={50}
                max={200}
              />
            </div>
          </div>

          {/* Energy Range */}
          <div className="space-y-3">
            <Label className="text-sm font-medium">
              Energy: {filters.minEnergy}% - {filters.maxEnergy}%
            </Label>
            <div className="flex items-center gap-3">
              <span className="text-xs text-muted-foreground w-8">{filters.minEnergy}%</span>
              <Slider
                value={[filters.minEnergy, filters.maxEnergy]}
                onValueChange={([min, max]) => setFilters(prev => ({ ...prev, minEnergy: min, maxEnergy: max }))}
                min={0}
                max={100}
                step={5}
                className="flex-1"
              />
              <span className="text-xs text-muted-foreground w-8">{filters.maxEnergy}%</span>
            </div>
          </div>

          {/* Danceability Range */}
          <div className="space-y-3">
            <Label className="text-sm font-medium">
              Danceability: {filters.minDance}% - {filters.maxDance}%
            </Label>
            <div className="flex items-center gap-3">
              <span className="text-xs text-muted-foreground w-8">{filters.minDance}%</span>
              <Slider
                value={[filters.minDance, filters.maxDance]}
                onValueChange={([min, max]) => setFilters(prev => ({ ...prev, minDance: min, maxDance: max }))}
                min={0}
                max={100}
                step={5}
                className="flex-1"
              />
              <span className="text-xs text-muted-foreground w-8">{filters.maxDance}%</span>
            </div>
          </div>

          {/* Controls Row */}
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Gem className="w-4 h-4 text-primary" />
                <Label htmlFor="underground" className="text-sm font-medium cursor-pointer">
                  Underground Only
                </Label>
              </div>
              <Switch
                id="underground"
                checked={filters.undergroundOnly}
                onCheckedChange={(checked) => setFilters(prev => ({ ...prev, undergroundOnly: checked }))}
              />
            </div>
            <p className="text-xs text-muted-foreground">
              Only show tracks with popularity &lt; 50
            </p>
            
            <div className="flex items-center gap-2 mt-4">
              <Label className="text-sm">Limit:</Label>
              <Input
                type="number"
                value={filters.limit}
                onChange={(e) => setFilters(prev => ({ ...prev, limit: Math.min(100, Math.max(10, Number(e.target.value))) }))}
                className="w-20 h-8 text-sm"
                min={10}
                max={100}
              />
              <span className="text-xs text-muted-foreground">tracks</span>
            </div>
          </div>
        </div>

        {/* Search Button */}
        <div className="flex gap-3">
          <Button 
            onClick={handleSearch} 
            disabled={isSearching}
            className="flex-1"
          >
            {isSearching ? (
              <>
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                Searching...
              </>
            ) : (
              <>
                <Filter className="w-4 h-4 mr-2" />
                Search Library
              </>
            )}
          </Button>
        </div>

        {/* Results */}
        {results.length > 0 && (
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <p className="text-sm font-medium text-foreground">
                {results.length} tracks found
              </p>
              <Button 
                onClick={handleCreatePlaylist}
                disabled={isCreatingPlaylist}
                size="sm"
                variant="outline"
              >
                {isCreatingPlaylist ? (
                  <>
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    Creating...
                  </>
                ) : (
                  <>
                    <PlayCircle className="w-4 h-4 mr-2" />
                    Create Playlist
                  </>
                )}
              </Button>
            </div>

            <ScrollArea className="h-[300px] rounded-md border">
              <div className="p-4 space-y-2">
                {results.map((track, i) => (
                  <div
                    key={track.track_id}
                    className="flex items-center gap-3 p-2 rounded-lg hover:bg-muted/50 transition-colors"
                  >
                    <span className="text-xs text-muted-foreground w-6">{i + 1}</span>
                    <Music2 className="w-4 h-4 text-muted-foreground flex-shrink-0" />
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium truncate">{track.name}</p>
                      <p className="text-xs text-muted-foreground truncate">{track.artist}</p>
                    </div>
                    <div className="flex items-center gap-2 flex-shrink-0">
                      {track.tempo && (
                        <Badge variant="secondary" className="text-xs">
                          {Math.round(track.tempo)} BPM
                        </Badge>
                      )}
                      {track.energy && (
                        <Badge variant="outline" className="text-xs">
                          {Math.round(track.energy * 100)}% E
                        </Badge>
                      )}
                      {track.popularity !== null && track.popularity < 50 && (
                        <Gem className="w-3 h-3 text-primary" />
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </ScrollArea>
          </div>
        )}
      </CardContent>
    </Card>
  );
};

export default SmartDiscoveryEngine;
